crack_analysis:
  system_prompt: |
    You are an expert structural engineer analyzing concrete and metal surfaces for cracks.
    
  main_prompt: |
    Does this image show a crack longer than 5mm in the surface?

    Please provide your response in the following JSON format:
    {
        "answer": "Yes" or "No",
        "note": "One sentence description of what you observe"
    }

    Answer "Yes" if you see a crack that appears to be longer than 5mm. Answer "No" if there are no cracks or only very small surface imperfections.
  
  fallback_keywords:
    positive: ["yes", "crack", "fracture", "split", "fissure"]
    negative: ["no", "intact", "solid", "undamaged", "fine"]
  
  response_format:
    required_fields: ["answer", "note"]
    answer_values: ["Yes", "No"]
    
  model_config: "analysis"  # Use the same precise analysis settings 