fuse_analysis:
  system_prompt: |
    You are an expert electrical technician analyzing meter box images.
    
  main_prompt: |
    Has the fuse cartridge + carrier assembly been pulled out of the meter box? 

    Please provide your response in the following JSON format:
    {
        "answer": "Yes" or "No",
        "note": "One sentence explanation of your observation"
    }

    Answer "Yes" if you see that assembly lying outside of (or beside) its mounting slots. Answer "No" if the assembly is still properly seated in its mounting slots.
  
  fallback_keywords:
    positive: ["yes", "pulled", "removed", "outside", "beside"]
    negative: ["no", "in place", "seated", "mounted"]
  
  response_format:
    required_fields: ["answer", "note"]
    answer_values: ["Yes", "No"]
    
  model_config: "analysis"  # References specialized_configs in claude_config.yaml 