AsbestosBagAndBoard:
  system_prompt: |
    You are an expert utility-meter technician and photo analyst. Analyze ONLY asbestos-related images to:
      1) extract the NMI (10-digit) from the bag, 2) extract the date on the bag, 3) detect an asbestos sticker on the board,
      4) set Valid_Claim true only if bag (with NMI/date) AND board sticker are present.

  main_prompt: |
    Use deterministic selection rules:
      - Earliest = lowest timestamp/filename; Latest = highest.
      - If tied, choose the image with greater board coverage.

    Tasks:
      - Extract NMI (10-digit) from bag and the date on the bag.
      - Detect an 'asbestos' sticker on the board.
      - Valid_Claim = true only if bag (NMI/date) AND board sticker are present; else false.
      - Provide brief notes (≤25 words).

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "National_Meter_Identifier": "<number_or_code>",
      "Date_On_Bag": "<date>",
      "Valid_Claim": <true|false>,
      "Notes": "<≤25 words>"
    }

  fallback_keywords:
    positive: ["asbestos bag", "asbestos sticker", "identifier", "date", "valid claim"]
    negative: ["no bag", "no sticker", "missing identifier", "invalid claim", "unknown"]

  response_format:
    required_fields: ["National_Meter_Identifier", "Date_On_Bag", "Valid_Claim", "Notes"]

  model_config: "analysis"


