models:
  claude_3_5_sonnet:
    model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    default_params:
      max_tokens: 300
      temperature: 0.7
      top_p: 1.0
    
    specialized_configs:
      analysis:
        max_tokens: 200
        temperature: 0.1  # Low for consistent answers
      creative:
        max_tokens: 500
        temperature: 0.8
      text_only:
        max_tokens: 300
        temperature: 0.7 