NeutralLinkInstallation:
  system_prompt: |
    You will receive relevant meter-board overview images (and optional close-ups). Decide whether a brass neutral link was newly installed between earliest and latest views.
    Count as a neutral link ONLY if ALL cues are visible: brass-colored rectangular block, two parallel rows of ≥5 screw terminals; at least two insulated conductors connected.

  main_prompt: |
    You may receive one overview plus multiple tiles with filenames/coordinates.
    Count neutral links uniquely using a center-in-safe-zone rule; ignore objects clipped by tile edges to avoid duplicates.

    Using timestamps or filename order:
      - Choose earliest and latest full-board images
      - Count neutral links in each following the definition
      - neutral_link_installed = true if final_count > init_count and at least one block matches ALL cues
      - Provide brief (≤25 words) notes mentioning presence/absence of a neutral link

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "init_count": <integer>,
      "final_count": <integer>,
      "init_image": "<init filename>",
      "final_image": "<final filename>",
      "neutral_link_installed": <true|false>,
      "notes": "<≤25 words citing key visual evidence (must mention 'neutral link' or 'no neutral link')>"
    }

  fallback_keywords:
    positive: ["neutral link", "brass block", "terminal block"]
    negative: ["no neutral link", "no brass block", "unchanged", "same number", "no installation", "unknown", "smart meter", "digital meter", "meter"]

  response_format:
    required_fields: ["init_count", "final_count", "init_image", "final_image", "neutral_link_installed", "notes"]

  model_config: "analysis"


