enabled: true
repository_path: 'data/reference_images'
max_reference_images: 20

# List of SOR types that have RAG enabled
enabled_sor_types:
  #- MeterConsolidationE4
  # Add more as you implement them:
  # - FuseReplacement
  # - PlugInMeterRemoval

reference_images:
  max_width: 800
  max_height: 800
  quality: 85