app:
  name: "IntelliHub SOR POC"
  version: "0.1.0"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
image_processing:
  default_resize:
    width: 900
    height: 900
  supported_formats: ["*.png", "*.jpg", "*.jpeg", "*.bmp", "*.gif", "*.tiff", "*.webp"]
  max_batch_size: 10
  default_format: "PNG"
  
analysis:
  concurrent_requests: 5
  default_timeout: 30
  
paths:
  default_image_folder: "artefacts/Fuse-Replacement-Examples" 
image_gridder:
  images_per_grid: 4         # e.g., 2x2 grid
  grid_width: 1200           # total width in pixels
  grid_height: 1200          # total height in pixels
  border_size: 10            # pixels between images
  background_color: "#FFFFFF" # white
  label_images: true         # add filename labels 