# Azure OpenAI Configuration
# This file contains all Azure-specific configuration settings

azure_openai:
  # Azure OpenAI endpoint (from your Azure portal)
  endpoint: "https://analyticsaitest.openai.azure.com/"
  
  # API version for Azure OpenAI
  api_version: "2024-02-15-preview"
  
  # Deployment name (the model deployment you created in Azure)
  deployment_name: "gpt-4o"
  
  # Key Vault configuration for secure credential management
  keyvault:
    name: "AnalyticsInsightsGenKV"
    # Authentication method will be implemented later (SSO/Fabric)
    # For now, you can use environment variables as fallback
    
  # Fallback authentication (environment variables)
  fallback_auth:
    api_key_env_var: "AZURE_OPENAI_API_KEY"
    endpoint_env_var: "AZURE_OPENAI_ENDPOINT"
    deployment_env_var: "AZURE_OPENAI_DEPLOYMENT"
    
  # Azure OpenAI model configuration
  models_config_file: "configs/models/azure_openai_config.yaml"
    
  # Pricing configuration (per 1K tokens)
  pricing:
    gpt-4o-mini:
      input_price_per_1k: 0.000165
      output_price_per_1k: 0.00066
    gpt-4o:
      input_price_per_1k: 0.0055
      output_price_per_1k: 0.0165
    gpt-35-turbo:
      input_price_per_1k: 0.00055
      output_price_per_1k: 0.00165
    o3:
      input_price_per_1k: 0.0022
      output_price_per_1k: 0.0088
      
  # Connection settings
  connection:
    max_pool_connections: 100
    connect_timeout: 60
    read_timeout: 300
    max_retries: 3
    
  # Image processing limits
  image_limits:
    max_size_mb: 20  # Azure OpenAI 20MB limit
    supported_formats: ["png", "jpg", "jpeg", "gif", "webp"]
