# SOR Analysis Configuration
# This file defines which SOR types to analyze and their specific parameters

sor_analysis:
  # Client type selection (aws or azure)
  client_type: "azure"  # Options: "aws" or "azure"
  
  # Default settings for all SOR analyses
  default_settings:
    output_format: "PNG"
    model_config: "analysis"
  # Use targeted prompts from nested folder
  prompt_subdir: "prompts/Targeted-Prompts"
    
  # Define available SOR types and their configurations
  sor_types:
    AsbestosBagAndBoard:
      enabled: true
      description: "Analyzes asbestos bag and meter board for asbestos claims"
      prompt_config: "AsbestosBagAndBoard"
      required_fields:
        - "National_Meter_Identifier"
        - "Date_On_Bag"
        - "Valid_Claim"
        - "Notes"
      
    CertificateOfCompliance:
      enabled: true
      description: "Analyzes meter board for compliance certificate"
      prompt_config: "CertificateOfCompliance"
      required_fields:
        - "Electrical_Work_Present"
        - "Valid_Certificate"
        - "Notes"
        
    FuseReplacement:
      enabled: true
      description: "Analyzes fuse replacement evidence"
      prompt_config: "FuseReplacement"
      required_fields:
        - "fuse_count"
        - "is_even_count"
        - "valid_claim"
        - "notes"
        
    MeterConsolidationE4:
      enabled: true
      description: "Analyzes meter consolidation E4 requirements"
      prompt_config: "MeterConsolidationE4"
      required_fields:
        - "init_count"
        - "final_count"
        - "consolidation"
        - "notes"
        
    PlugInMeterRemoval:
      enabled: true
      description: "Analyzes plug-in meter removal evidence"
      prompt_config: "PlugInMeterRemoval"
      required_fields:
        - "init_count"
        - "final_count"
        - "meters_removed"
        - "notes"
        
    ServiceProtectionDevices:
      enabled: true
      description: "Analyzes service protection device installation"
      prompt_config: "ServiceProtectionDevices"
      required_fields:
        - "init_count"
        - "final_count"
        - "devices_added"
        - "notes"
        
    SwitchInstallation:
      enabled: true
      description: "Analyzes switch installation evidence"
      prompt_config: "SwitchInstallation"
      required_fields:
        - "switch_installed"
        - "switch_count"
        - "notes"
        
    NeutralLinkInstallation:
      enabled: true
      description: "Analyzes neutral link installation evidence"
      prompt_config: "NeutralLinkInstallation"
      required_fields:
        - "init_count"
        - "final_count"
        - "neutral_link_installed"
        - "notes"
        
    meter_reading:
      enabled: true
      description: "Analyzes meter readings from utility meters"
      prompt_config: "meter_reading"
      required_fields:
        - "most_likely"
        - "possible_values"
        - "meter_type"
        - "confidence"
        - "notes"


  # Output configuration
  output:
    format: "json"
    save_to_file: true
    output_dir: "artefacts/sor_results"
    
  # Default folder paths
  default_paths:
    single_sor_image_folder: "artefacts/Fuse-Replacement-Examples"
    batch_parent_folder: "C:/Users/George.Nizoridis/OneDrive - Service Stream/Admin/Intellihub AI Analysis/All-WOs - Copy"
    batch_output_folder: "outputs/batch_results"
    
  # Batch processing configuration
  batch_processing:
    work_order_pattern: r"(WO-[A-Z0-9]+)"  # Extract full work order numbers like WO-EAC2505021264593
    exclude_patterns: ["__pycache__", ".git", "test_grids", "sor_results", "Archive"]
    min_images_per_work_order: 1
    max_work_orders: 10  # null = no limit (process all work orders)
    test_max_work_orders: 5  # Default test limit when --test-mode is used
    parallel_processing: true
    max_concurrent_work_orders: 8  # Increased from 3 to 8 for better throughput
    max_concurrent_sor_types: 9  # Process up to 8 SOR types concurrently within each work order (was 4)
    api_rate_limit_delay: 0.3  # No delay - we're well under rate limits with optimized connection pooling
    batch_size: 5  # Number of work orders to process in each memory batch (prevents OOM issues)

  # Targeted image feeding configuration
  targeted_images:
    enabled: true
    default_folder: "Meter Board"
    # Optional cap to reduce per-SOR payload size and speed up processing
    max_images_per_sor: 6
    folder_mapping:
      MeterConsolidationE4: ["Meter Board"]
      PlugInMeterRemoval: ["Meter Board"]
      ServiceProtectionDevices: ["Meter Board"]
      SwitchInstallation: ["Switch", "Meter Board"]
      NeutralLinkInstallation: ["Link Replacement", "Meter Board"]
      FuseReplacement: ["Fuze"]
      CertificateOfCompliance: ["Compliance"]
      AsbestosBagAndBoard: ["Asbestos"]
      meter_reading: ["Meter Board"]
    
  # CLI configuration defaults
  cli_defaults:
    test_mode: false
    output_format: "both"  # csv, excel, both
    save_json: true
    max_work_orders: null  # cap default processing to 10 work orders
    parent_folder: null    # null = use default_paths.batch_parent_folder
    output_path: null      # null = use default_paths.batch_output_folder with timestamp
    sor_list: null         # null = use all enabled
    list_sors: false       # false = normal processing, true = list SOR types and exit

  # Table generation configuration
  table_generation:
    boolean_fields:
      AsbestosBagAndBoard: "Valid_Claim"
      CertificateOfCompliance: "Valid_Certificate"
      FuseReplacement: "valid_claim"
      MeterConsolidationE4: "consolidation"
      PlugInMeterRemoval: "meters_removed"
      ServiceProtectionDevices: "devices_added"
      SwitchInstallation: "switch_installed"
      NeutralLinkInstallation: "neutral_link_installed"
      meter_reading: "most_likely"
    notes_fields:
      AsbestosBagAndBoard: "Notes"
      CertificateOfCompliance: "Notes"
      FuseReplacement: "notes"
      MeterConsolidationE4: "notes"
      PlugInMeterRemoval: "notes"
      ServiceProtectionDevices: "notes"
      SwitchInstallation: "notes"
      NeutralLinkInstallation: "notes"
      meter_reading: "notes"
    additional_fields:
      AsbestosBagAndBoard: ["National_Meter_Identifier", "Date_On_Bag"]
      CertificateOfCompliance: ["Electrical_Work_Present"]
      FuseReplacement: ["fuse_count", "is_even_count"]
      MeterConsolidationE4: ["init_count", "final_count"]
      PlugInMeterRemoval: ["init_count", "final_count"]
      ServiceProtectionDevices: ["init_count", "final_count"]
      SwitchInstallation: ["switch_count"]
      NeutralLinkInstallation: ["init_count", "final_count"]
      meter_reading: ["possible_values", "meter_type", "confidence"]
    output_formats: ["csv", "excel"]
    include_metadata: true
    include_costs: true
    sort_by_work_order: true 