# SOR Analysis Configuration
# This file defines which SOR types to analyze and their specific parameters

sor_analysis:
  # Default settings for all SOR analyses
  default_settings:
    use_image_grids: true
    output_format: "PNG"
    grid_output_dir: "artefacts/test_grids"
    model_config: "analysis"
    
  # Define available SOR types and their configurations
  sor_types:
    AsbestosBagAndBoard:
      enabled: true
      description: "Analyzes asbestos bag and meter board for asbestos claims"
      prompt_config: "AsbestosBagAndBoard"
      required_fields:
        - "Asbestos_bag_image"
        - "Meter_board_image" 
        - "National_Meter_Identifier"
        - "Date_On_Bag"
        - "Valid_Claim"
        - "Notes"
      
    CertificateOfCompliance:
      enabled: true
      description: "Analyzes meter board for compliance certificate"
      prompt_config: "CertificateOfCompliance"
      required_fields:
        - "certificate_image"
        - "certificate_number"
        - "issue_date"
        - "compliance_status"
        - "notes"
        
    FuseReplacement:
      enabled: true
      description: "Analyzes fuse replacement evidence"
      prompt_config: "FuseReplacement"
      required_fields:
        - "fuse_image"
        - "fuse_count"
        - "is_even_count"
        - "valid_claim"
        - "notes"
        
    MeterConsolidationE4:
      enabled: true
      description: "Analyzes meter consolidation E4 requirements"
      prompt_config: "MeterConsolidationE4"
      required_fields:
        - "consolidation_image"
        - "meter_count"
        - "consolidation_type"
        - "valid_consolidation"
        - "notes"
        
    PlugInMeterRemoval:
      enabled: true
      description: "Analyzes plug-in meter removal evidence"
      prompt_config: "PlugInMeterRemoval"
      required_fields:
        - "removal_image"
        - "meter_type"
        - "removal_method"
        - "valid_removal"
        - "notes"
        
    ServiceProtectionDevices:
      enabled: true
      description: "Analyzes service protection device installation"
      prompt_config: "ServiceProtectionDevices"
      required_fields:
        - "device_image"
        - "device_type"
        - "installation_status"
        - "valid_installation"
        - "notes"
        
    SwitchInstallation:
      enabled: true
      description: "Analyzes switch installation evidence"
      prompt_config: "SwitchInstallation"
      required_fields:
        - "switch_image"
        - "switch_type"
        - "installation_status"
        - "valid_installation"
        - "notes"
        
    NeutralLinkInstallation:
      enabled: true
      description: "Analyzes neutral link installation evidence"
      prompt_config: "NeutralLinkInstallation"
      required_fields:
        - "link_image"
        - "link_type"
        - "installation_status"
        - "valid_installation"
        - "notes"
        
    meter_reading:
      enabled: true
      description: "Analyzes meter readings from utility meters"
      prompt_config: "meter_reading"
      required_fields:
        - "meter_image"
        - "reading_value"
        - "reading_date"
        - "meter_type"
        - "notes"

  # Analysis modes
  analysis_modes:
    single_sor:
      description: "Analyze a single SOR type"
      usage: "python sor_analysis.py --sor-type <SOR_TYPE> [--image-folder <PATH>]"
      
    multi_sor:
      description: "Analyze multiple SOR types (all enabled SORs)"
      usage: "python sor_analysis.py --multi-sor [--image-folder <PATH>]"
      
    custom_sor_list:
      description: "Analyze specific SOR types from a list"
      usage: "python sor_analysis.py --sor-list <SOR1,SOR2,SOR3> [--image-folder <PATH>]"

  # Output configuration
  output:
    format: "json"
    include_metadata: true
    include_costs: true
    save_to_file: true
    output_dir: "artefacts/sor_results"
    
  # Default folder paths
  default_paths:
    single_sor_image_folder: "artefacts/Fuse-Replacement-Examples"
    batch_parent_folder: "C:/Users/George.Nizoridis/OneDrive - Service Stream/Admin/Intellihub AI Analysis/All-WOs"
    batch_output_folder: "artefacts/batch_results"
    
  # Batch processing configuration
  batch_processing:
    work_order_pattern: r"(WO-[A-Z0-9]+)"  # Extract full work order numbers like WO-EAC2505021264593
    exclude_patterns: ["__pycache__", ".git", "test_grids", "sor_results", "Archive"]
    min_images_per_work_order: 1
    max_work_orders: null  # null = no limit
    parallel_processing: true
    max_concurrent_work_orders: 3
    
  # Table generation configuration
  table_generation:
    boolean_fields:
      AsbestosBagAndBoard: "Valid_Claim"
      CertificateOfCompliance: "compliance_status"
      FuseReplacement: "valid_claim"
      MeterConsolidationE4: "valid_consolidation"
      PlugInMeterRemoval: "valid_removal"
      ServiceProtectionDevices: "valid_installation"
      SwitchInstallation: "valid_installation"
      NeutralLinkInstallation: "valid_installation"
      meter_reading: "valid_reading"
    notes_fields:
      AsbestosBagAndBoard: "Notes"
      CertificateOfCompliance: "notes"
      FuseReplacement: "notes"
      MeterConsolidationE4: "notes"
      PlugInMeterRemoval: "notes"
      ServiceProtectionDevices: "notes"
      SwitchInstallation: "notes"
      NeutralLinkInstallation: "notes"
      meter_reading: "notes"
    additional_fields:
      AsbestosBagAndBoard: ["National_Meter_Identifier", "Date_On_Bag"]
      CertificateOfCompliance: ["certificate_number", "issue_date"]
      FuseReplacement: ["fuse_count", "is_even_count"]
      MeterConsolidationE4: ["meter_count", "consolidation_type"]
      PlugInMeterRemoval: ["meter_type", "removal_method"]
      ServiceProtectionDevices: ["device_type", "installation_status"]
      SwitchInstallation: ["switch_type", "installation_status"]
      NeutralLinkInstallation: ["link_type", "installation_status"]
      meter_reading: ["reading_value", "reading_date", "meter_type"]
    output_formats: ["csv", "excel"]
    include_metadata: true
    include_costs: true
    sort_by_work_order: true 