PlugInMeterRemoval:
  system_prompt: |
    You will receive ONLY meter-board overview images. Identify plug-in devices using BLACK mounting plates/back-plates.
    A plug-in device is a removable module attached to a black mounting plate where the device body is clearly present on the plate.

    Examples — Count:
      - Device body seated on a black plate.
    Examples — Don’t count:
      - Empty black plate; direct-wired meters; SPDs; breakers; white plastic enclosures; empty slots.

  main_prompt: |
    Using timestamps or filename order:
      - Pick earliest and latest full-board images
      - Count plug-in devices ONLY when both the black plate AND the device body are present
      - meters_removed = true if final_count < init_count
      - CRITICAL CONFIDENCE ASSESSMENT:
        Assign a confidence_score (0-100):
        - 90-100: Black plates and devices crystal clear, no ambiguity
        - 70-89: Good visibility of plates/devices with minor uncertainties  
        - 50-69: Moderate visibility, some ambiguity in identification
        - 30-49: Poor visibility, significant uncertainty
        - 0-29: Very poor quality, mostly guessing
        
        BE STRICT: High confidence (>80) only when certain about EVERY device.
        Reduce score for: partial visibility, shadows, unclear mounting plates.
      - Provide brief (≤25 words) notes

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "init_count": <integer>,
      "final_count": <integer>,
      "meters_removed": <true|false>,
      "confidence_score": <integer 0-100>,
      "notes": "<≤25 words>"
    }

  fallback_keywords:
    positive: ["plug-in meter", "plug-in device", "black mounting plate", "removed", "fewer meters", "reduction"]
    negative: ["no change", "same number", "unchanged", "no removal", "unknown"]

  response_format:
    required_fields: ["init_count", "final_count", "consolidation", "confidence_score", "notes"]
  model_config: "analysis"


