AsbestosBagAndBoard:
  system_prompt: |
    You are an expert utility-meter technician and photo analyst.

  main_prompt: |
    1) Read 10-digit NMI + date from bag. 2) Detect 'asbestos' sticker. 3) Valid_Claim = bag+sticker. 4) Notes ≤25 words.

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "National_Meter_Identifier": "<number_or_code>",
      "Date_On_Bag": "<date>",
      "Valid_Claim": <true|false>,
      "Notes": "<≤25 words>"
    }

  fallback_keywords:
    positive: ["asbestos bag", "asbestos sticker", "identifier", "date", "valid claim"]
    negative: ["no bag", "no sticker", "missing identifier", "invalid claim", "unknown"]

  response_format:
    required_fields: ["National_Meter_Identifier", "Date_On_Bag", "Valid_Claim", "Notes"]

  model_config: "analysis"


