FuseReplacement:
  system_prompt: |
    You are an expert electrical technician.

  main_prompt: |
    1) Pick image with most barrels. 2) Count visible barrels only. 3) Even = valid. 4) Notes ≤25 words.

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "fuse_image": "<filename_of_image_showing_most_fuses>",
      "fuse_count": <integer_total_number_of_fuses>,
      "is_even_count": <true|false>,
      "valid_claim": <true|false>,
      "notes": "<brief (≤25 words) justification mentioning key visual evidence>"
    }

  fallback_keywords:
    positive: ["fuses", "even count", "replacement", "valid claim", "clear image", "cylindrical", "printed", "label", "barrel", "cartridge"]
    negative: ["no fuses", "odd count", "invalid claim", "unclear", "missing", "unknown", "holder only", "empty holder"]

  response_format:
    required_fields: ["fuse_image", "fuse_count", "is_even_count", "valid_claim", "notes"]

  model_config: "analysis"


