PlugInMeterRemoval:
  system_prompt: |
    You are an expert electrical technician.

  main_prompt: |
    1) Earliest vs latest. 2) Count plug-ins only when body on black plate. 3) removed = final<init. 4) Notes ≤25 words.

    Return EXACTLY this JSON (no extra keys, no markdown):
    {
      "init_count": <integer>,
      "final_count": <integer>,
      "meters_removed": <true|false>,
      "notes": "<≤25 words>"
    }

  fallback_keywords:
    positive: ["plug-in meter", "plug-in device", "black mounting plate", "removed", "fewer meters", "reduction"]
    negative: ["no change", "same number", "unchanged", "no removal", "unknown"]

  response_format:
    required_fields: ["init_count", "final_count", "meters_removed", "notes"]

  model_config: "analysis"


